[package]
name = "zync-adapters"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zync-core.workspace = true
anyhow.workspace = true
dirs.workspace = true
hostname.workspace = true
rumqttc.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tracing.workspace = true
